### ISSUE TITLE
Not working with attiny25/45/85

### ISSUE THREAD

**Issue by wareck** [wagiminator/ATtiny84-TinyHVSP#2]
I don't understand, it work perfectly with attiny13 but with tiny25 or tiny45 it do not work.
Have you got an idea to fix this ?

**Comment by wagiminator** [comment]
That's weird. Can you otherwise program the ATtiny25/45 normally?

**Comment by wareck** [comment]
Hello
sorry this message was old, I found why not working.
It's because I had some attiny25 which not have same signatures (probably fake or re-branded chips)
I add a case switch for these weird signature and works like a charm
 
 I also add a dip socket and connections for attiny84 with the same design/software , I just add some line to recogneize chip and give right fuse for attiny84
 
 thanks you a lot 
 you cas close this issue 

best regards
Olivier

**Comment by wagiminator** [comment]
Well that sounds good, thank you very much!
